module Main where

import Apripsql.Queries
import Data.Set (Set)
import qualified Data.Set as S
import Data.Text (Text)
import qualified Data.Text as T
import Database.PostgreSQL.Simple
import Issues (testAllIssues)
import Setup.Game (Game (..))
import System.Environment (lookupEnv)
import Test.Tasty
import Test.Tasty.HUnit
import Utils (withConnString)

main :: IO ()
main =
  defaultMain $ testGroup "All tests" [testAllIssues, testRandoms]

wc :: (Connection -> IO a) -> IO a
wc actn = do
  connString <- lookupEnv "FLY_PG_PROXY_CONN_STRING"
  case connString of
    Nothing -> error "FLY_PG_PROXY_CONN_STRING not set"
    Just cs -> withConnString (T.pack cs) actn

testRandoms :: TestTree
testRandoms =
  testGroup
    "Random tests"
    [ testTogeSwShEMParents "Togepi",
      testTogeSwShEMParents "Togetic",
      testTogeSwShEMParents "Togekiss"
    ]

testTogeSwShEMParents :: Text -> TestTree
testTogeSwShEMParents name = testCase (T.unpack name <> " SwSh EM parents") $ wc $ \conn -> do
  search <- getPokemon name conn
  case search of
    FoundOne dbPkmn -> do
      let pkmnId = dbId dbPkmn
      parents <- getEMParents SwSh pkmnId conn
      let aerialAceParents = case filter (\p -> emName (empMove p) == "Aerial Ace") parents of
            [p] -> empParents p
            _ -> error "Aerial Ace not found"
      assertEqual
        "Aerial Ace parents"
        ( S.fromList
            [ LevelUpParent "Farfetch'd" 20,
              LevelUpParent "Rufflet" 30,
              LevelUpParent "Braviary" 30,
              LevelUpParent "Fletchling" 30,
              LevelUpParent "Fletchinder" 36,
              LevelUpParent "Talonflame" 38,
              LevelUpParent "Hawlucha" 12,
              BreedParent "Togetic",
              BreedParent "Togekiss",
              BreedParent "Wingull",
              BreedParent "Pelipper",
              BreedParent "Cramorant"
            ]
        )
        (S.fromList aerialAceParents)
    _ -> error $ "Pokemon " ++ T.unpack name ++ " not found"

-- Helpers

-- findMon :: Text -> Maybe Text -> [PokemonPartial] -> PokemonPartial
-- findMon name form pp = case filter
--   ( \pkmn ->
--       pname pkmn == name
--         && pform pkmn == form
--   )
--   pp of
--   [pkmn] -> pkmn
--   [] -> error ("Couldn't find " <> T.unpack name)
--   _ -> error "Multiple Pokemon with the same name"

-- Tests

-- tests :: [PokemonPartial] -> TestTree
-- tests p =
--   testGroup
--     "Unit tests"
--     [ testCharmander p,
--       testVulpix p,
--       testAlolanVulpix p,
--       testSobble p,
--       testRattata p,
--       testAlolanRattata p
--     ]

-- testRattata :: [PokemonPartial] -> TestTree
-- testRattata pkmnPartial =
--   let rat = findMon "Rattata" Nothing pkmnPartial
--    in testGroup
--         "Rattata"
--         [testCase "USUM" (testRattataUSUM rat)]

-- testRattataUSUM :: PokemonPartial -> Assertion
-- testRattataUSUM rat = do
--   let usumCorrect =
--         [ MoveLearn {mldMoveName = "Tackle", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Tail Whip", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Quick Attack", mldLearnMethod = LevelUp 4},
--           MoveLearn {mldMoveName = "Focus Energy", mldLearnMethod = LevelUp 7},
--           MoveLearn {mldMoveName = "Bite", mldLearnMethod = LevelUp 10},
--           MoveLearn {mldMoveName = "Pursuit", mldLearnMethod = LevelUp 13},
--           MoveLearn {mldMoveName = "Hyper Fang", mldLearnMethod = LevelUp 16},
--           MoveLearn {mldMoveName = "Assurance", mldLearnMethod = LevelUp 19},
--           MoveLearn {mldMoveName = "Crunch", mldLearnMethod = LevelUp 22},
--           MoveLearn {mldMoveName = "Sucker Punch", mldLearnMethod = LevelUp 25},
--           MoveLearn {mldMoveName = "Super Fang", mldLearnMethod = LevelUp 28},
--           MoveLearn {mldMoveName = "Double-Edge", mldLearnMethod = LevelUp 31},
--           MoveLearn {mldMoveName = "Endeavor", mldLearnMethod = LevelUp 34},
--           MoveLearn {mldMoveName = "Bite", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Counter", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Final Gambit", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Flame Wheel", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Fury Swipes", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Last Resort", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Me First", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Revenge", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Reversal", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Screech", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Uproar", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Covet", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Endeavor", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Icy Wind", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Iron Tail", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Last Resort", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Shock Wave", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Snore", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Super Fang", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Uproar", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Zen Headbutt", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Work Up", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Toxic", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Hidden Power", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sunny Day", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Taunt", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Ice Beam", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Blizzard", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Protect", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rain Dance", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Frustration", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Thunderbolt", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Thunder", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Return", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Shadow Ball", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Double Team", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Facade", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rest", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Attract", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Thief", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Round", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Charge Beam", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Thunder Wave", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Grass Knot", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Swagger", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sleep Talk", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "U-turn", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Substitute", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Wild Charge", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Confide", mldLearnMethod = TM}
--         ]
--   usum <- getLearnset rat USUM
--   usumCorrect @=? usum

-- testAlolanRattata :: [PokemonPartial] -> TestTree
-- testAlolanRattata pkmnPartial =
--   let arat = findMon "Rattata" (Just "Alolan Rattata") pkmnPartial
--    in testGroup
--         "Alolan Rattata"
--         [testCase "USUM" (testAlolanRattataUSUM arat)]

-- testAlolanRattataUSUM :: PokemonPartial -> Assertion
-- testAlolanRattataUSUM arat = do
--   let usumCorrect =
--         [ MoveLearn {mldMoveName = "Tackle", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Tail Whip", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Quick Attack", mldLearnMethod = LevelUp 4},
--           MoveLearn {mldMoveName = "Focus Energy", mldLearnMethod = LevelUp 7},
--           MoveLearn {mldMoveName = "Bite", mldLearnMethod = LevelUp 10},
--           MoveLearn {mldMoveName = "Pursuit", mldLearnMethod = LevelUp 13},
--           MoveLearn {mldMoveName = "Hyper Fang", mldLearnMethod = LevelUp 16},
--           MoveLearn {mldMoveName = "Assurance", mldLearnMethod = LevelUp 19},
--           MoveLearn {mldMoveName = "Crunch", mldLearnMethod = LevelUp 22},
--           MoveLearn {mldMoveName = "Sucker Punch", mldLearnMethod = LevelUp 25},
--           MoveLearn {mldMoveName = "Super Fang", mldLearnMethod = LevelUp 28},
--           MoveLearn {mldMoveName = "Double-Edge", mldLearnMethod = LevelUp 31},
--           MoveLearn {mldMoveName = "Endeavor", mldLearnMethod = LevelUp 34},
--           MoveLearn {mldMoveName = "Counter", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Final Gambit", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Fury Swipes", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Me First", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Revenge", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Reversal", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Snatch", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Stockpile", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Swallow", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Switcheroo", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Uproar", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Covet", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Endeavor", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Icy Wind", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Iron Tail", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Last Resort", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Shock Wave", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Snatch", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Snore", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Super Fang", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Uproar", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Zen Headbutt", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Toxic", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Hidden Power", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sunny Day", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Taunt", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Ice Beam", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Blizzard", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Protect", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rain Dance", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Frustration", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Return", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Shadow Ball", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Double Team", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sludge Bomb", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Torment", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Facade", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rest", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Attract", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Thief", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Round", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Quash", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Embargo", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Shadow Claw", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Grass Knot", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Swagger", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sleep Talk", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "U-turn", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Substitute", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Snarl", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dark Pulse", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Confide", mldLearnMethod = TM}
--         ]
--   usum <- getLearnset arat USUM
--   usumCorrect @=? usum

-- testCharizard :: [PokemonPartial] -> TestTree
-- testCharizard pkmnPartial =
--   let zard = findMon "Charizard" Nothing pkmnPartial
--    in testGroup
--         "Charizard"
--         [testCase "USUM" (testCharizardUSUM zard)]

-- testCharizardUSUM :: PokemonPartial -> Assertion
-- testCharizardUSUM zard = do
--   let usumCorrect =
--         [ MoveLearn {mldMoveName = "Air Slash", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Dragon Claw", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Ember", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Flare Blitz", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Growl", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Heat Wave", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Scratch", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Shadow Claw", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Wing Attack", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Ember", mldLearnMethod = LevelUp 7},
--           MoveLearn {mldMoveName = "Smokescreen", mldLearnMethod = LevelUp 10},
--           MoveLearn {mldMoveName = "Dragon Rage", mldLearnMethod = LevelUp 17},
--           MoveLearn {mldMoveName = "Scary Face", mldLearnMethod = LevelUp 21},
--           MoveLearn {mldMoveName = "Fire Fang", mldLearnMethod = LevelUp 28},
--           MoveLearn {mldMoveName = "Flame Burst", mldLearnMethod = LevelUp 32},
--           MoveLearn {mldMoveName = "Slash", mldLearnMethod = LevelUp 41},
--           MoveLearn {mldMoveName = "Flamethrower", mldLearnMethod = LevelUp 47},
--           MoveLearn {mldMoveName = "Fire Spin", mldLearnMethod = LevelUp 56},
--           MoveLearn {mldMoveName = "Inferno", mldLearnMethod = LevelUp 62},
--           MoveLearn {mldMoveName = "Heat Wave", mldLearnMethod = LevelUp 71},
--           MoveLearn {mldMoveName = "Flare Blitz", mldLearnMethod = LevelUp 77},
--           MoveLearn {mldMoveName = "Wing Attack", mldLearnMethod = Evolution},
--           MoveLearn {mldMoveName = "Air Cutter", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Ancient Power", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Beat Up", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Belly Drum", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Bite", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Counter", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Crunch", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Dragon Dance", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Dragon Pulse", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Dragon Rush", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Flare Blitz", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Focus Punch", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Metal Claw", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Outrage", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Blast Burn", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Defog", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Dragon Pulse", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Fire Pledge", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Fire Punch", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Focus Punch", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Heat Wave", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Iron Tail", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Outrage", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Snore", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Tailwind", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Thunder Punch", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Work Up", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dragon Claw", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Roar", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Toxic", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Hidden Power", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sunny Day", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Hyper Beam", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Protect", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Roost", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Frustration", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Solar Beam", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Earthquake", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Return", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Brick Break", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Double Team", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Flamethrower", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fire Blast", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rock Tomb", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Aerial Ace", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Facade", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Flame Charge", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rest", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Attract", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Round", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Echoed Voice", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Overheat", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Steel Wing", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Focus Blast", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fling", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sky Drop", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Brutal Swing", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Will-O-Wisp", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Shadow Claw", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Giga Impact", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Swords Dance", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fly", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Bulldoze", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rock Slide", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dragon Tail", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Swagger", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sleep Talk", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Substitute", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Confide", mldLearnMethod = TM}
--         ]
--   usum <- getLearnset zard USUM
--   usumCorrect @=? usum

-- testVulpix :: [PokemonPartial] -> TestTree
-- testVulpix pkmnPartial =
--   let vulp = findMon "Vulpix" Nothing pkmnPartial
--    in testGroup
--         "Vulpix"
--         [ testCase "USUM" (testVulpixUSUM vulp),
--           testCase "SWSH" (testVulpixSWSH vulp),
--           testCase "BDSP" (testVulpixBDSP vulp),
--           testCase "SV" (testVulpixSV vulp)
--         ]

-- testVulpixUSUM :: PokemonPartial -> Assertion
-- testVulpixUSUM vulp = do
--   let usumCorrect =
--         [ MoveLearn {mldMoveName = "Ember", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Tail Whip", mldLearnMethod = LevelUp 4},
--           MoveLearn {mldMoveName = "Roar", mldLearnMethod = LevelUp 7},
--           MoveLearn {mldMoveName = "Baby-Doll Eyes", mldLearnMethod = LevelUp 9},
--           MoveLearn {mldMoveName = "Quick Attack", mldLearnMethod = LevelUp 10},
--           MoveLearn {mldMoveName = "Confuse Ray", mldLearnMethod = LevelUp 12},
--           MoveLearn {mldMoveName = "Fire Spin", mldLearnMethod = LevelUp 15},
--           MoveLearn {mldMoveName = "Payback", mldLearnMethod = LevelUp 18},
--           MoveLearn {mldMoveName = "Will-O-Wisp", mldLearnMethod = LevelUp 20},
--           MoveLearn {mldMoveName = "Feint Attack", mldLearnMethod = LevelUp 23},
--           MoveLearn {mldMoveName = "Hex", mldLearnMethod = LevelUp 26},
--           MoveLearn {mldMoveName = "Flame Burst", mldLearnMethod = LevelUp 28},
--           MoveLearn {mldMoveName = "Extrasensory", mldLearnMethod = LevelUp 31},
--           MoveLearn {mldMoveName = "Safeguard", mldLearnMethod = LevelUp 34},
--           MoveLearn {mldMoveName = "Flamethrower", mldLearnMethod = LevelUp 36},
--           MoveLearn {mldMoveName = "Imprison", mldLearnMethod = LevelUp 39},
--           MoveLearn {mldMoveName = "Fire Blast", mldLearnMethod = LevelUp 42},
--           MoveLearn {mldMoveName = "Grudge", mldLearnMethod = LevelUp 44},
--           MoveLearn {mldMoveName = "Captivate", mldLearnMethod = LevelUp 47},
--           MoveLearn {mldMoveName = "Inferno", mldLearnMethod = LevelUp 50},
--           MoveLearn {mldMoveName = "Captivate", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Disable", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Extrasensory", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Feint Attack", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Flail", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Flare Blitz", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Heat Wave", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Hex", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Howl", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Hypnosis", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Power Swap", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Secret Power", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Spite", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Tail Slap", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Covet", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Foul Play", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Heat Wave", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Iron Tail", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Pain Split", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Role Play", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Snore", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Spite", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Zen Headbutt", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Roar", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Toxic", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Hidden Power", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sunny Day", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Protect", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Safeguard", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Frustration", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Return", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Double Team", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Flamethrower", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fire Blast", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Facade", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Flame Charge", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rest", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Attract", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Round", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Overheat", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Energy Ball", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Will-O-Wisp", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Payback", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Psych Up", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Swagger", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sleep Talk", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Substitute", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dark Pulse", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Confide", mldLearnMethod = TM}
--         ]
--   usum <- getLearnset vulp USUM
--   usumCorrect @=? usum

-- testVulpixSWSH :: PokemonPartial -> Assertion
-- testVulpixSWSH vulp = do
--   let swshCorrect =
--         [ MoveLearn {mldMoveName = "Ember", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Tail Whip", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Disable", mldLearnMethod = LevelUp 4},
--           MoveLearn {mldMoveName = "Quick Attack", mldLearnMethod = LevelUp 8},
--           MoveLearn {mldMoveName = "Spite", mldLearnMethod = LevelUp 12},
--           MoveLearn {mldMoveName = "Incinerate", mldLearnMethod = LevelUp 16},
--           MoveLearn {mldMoveName = "Confuse Ray", mldLearnMethod = LevelUp 20},
--           MoveLearn {mldMoveName = "Will-O-Wisp", mldLearnMethod = LevelUp 24},
--           MoveLearn {mldMoveName = "Extrasensory", mldLearnMethod = LevelUp 28},
--           MoveLearn {mldMoveName = "Flamethrower", mldLearnMethod = LevelUp 32},
--           MoveLearn {mldMoveName = "Imprison", mldLearnMethod = LevelUp 36},
--           MoveLearn {mldMoveName = "Fire Spin", mldLearnMethod = LevelUp 40},
--           MoveLearn {mldMoveName = "Safeguard", mldLearnMethod = LevelUp 44},
--           MoveLearn {mldMoveName = "Inferno", mldLearnMethod = LevelUp 48},
--           MoveLearn {mldMoveName = "Grudge", mldLearnMethod = LevelUp 52},
--           MoveLearn {mldMoveName = "Fire Blast", mldLearnMethod = LevelUp 56},
--           MoveLearn {mldMoveName = "Baby-Doll Eyes", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Flail", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Flame Charge", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Howl", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Hypnosis", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Memento", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Roar", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Burning Jealousy", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Fire Spin", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dig", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Safeguard", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rest", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Snore", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Protect", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Attract", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sunny Day", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Will-O-Wisp", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Facade", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Swift", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Imprison", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Weather Ball", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Payback", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Power Swap", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Round", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Hex", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Tail Slap", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Mystical Fire", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Body Slam", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Flamethrower", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Agility", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fire Blast", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Substitute", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Endure", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sleep Talk", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Encore", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Iron Tail", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Heat Wave", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Overheat", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Flare Blitz", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dark Pulse", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Energy Ball", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Zen Headbutt", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Foul Play", mldLearnMethod = TM}
--         ]
--   swsh <- getLearnset vulp SWSH
--   swshCorrect @=? swsh

-- testVulpixBDSP :: PokemonPartial -> Assertion
-- testVulpixBDSP vulp = do
--   let bdspCorrect =
--         [ MoveLearn {mldMoveName = "Ember", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Tail Whip", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Disable", mldLearnMethod = LevelUp 4},
--           MoveLearn {mldMoveName = "Quick Attack", mldLearnMethod = LevelUp 8},
--           MoveLearn {mldMoveName = "Spite", mldLearnMethod = LevelUp 12},
--           MoveLearn {mldMoveName = "Incinerate", mldLearnMethod = LevelUp 16},
--           MoveLearn {mldMoveName = "Confuse Ray", mldLearnMethod = LevelUp 20},
--           MoveLearn {mldMoveName = "Will-O-Wisp", mldLearnMethod = LevelUp 24},
--           MoveLearn {mldMoveName = "Extrasensory", mldLearnMethod = LevelUp 28},
--           MoveLearn {mldMoveName = "Flamethrower", mldLearnMethod = LevelUp 32},
--           MoveLearn {mldMoveName = "Imprison", mldLearnMethod = LevelUp 36},
--           MoveLearn {mldMoveName = "Fire Spin", mldLearnMethod = LevelUp 40},
--           MoveLearn {mldMoveName = "Safeguard", mldLearnMethod = LevelUp 44},
--           MoveLearn {mldMoveName = "Inferno", mldLearnMethod = LevelUp 48},
--           MoveLearn {mldMoveName = "Grudge", mldLearnMethod = LevelUp 52},
--           MoveLearn {mldMoveName = "Fire Blast", mldLearnMethod = LevelUp 56},
--           MoveLearn {mldMoveName = "Baby-Doll Eyes", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Disable", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Extrasensory", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Flail", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Flame Charge", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Flare Blitz", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Heat Wave", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Hex", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Howl", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Hypnosis", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Memento", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Power Swap", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Spite", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Roar", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sunny Day", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Protect", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Safeguard", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Iron Tail", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dig", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Double Team", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Flamethrower", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fire Blast", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Facade", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rest", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Attract", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Overheat", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Energy Ball", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Endure", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Will-O-Wisp", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Payback", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Psych Up", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dark Pulse", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sleep Talk", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Swagger", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Substitute", mldLearnMethod = TM}
--         ]
--   bdsp <- getLearnset vulp BDSP
--   bdspCorrect @=? bdsp

-- testVulpixSV :: PokemonPartial -> Assertion
-- testVulpixSV vulp = do
--   let svCorrect =
--         [ MoveLearn {mldMoveName = "Ember", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Tail Whip", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Disable", mldLearnMethod = LevelUp 4},
--           MoveLearn {mldMoveName = "Quick Attack", mldLearnMethod = LevelUp 8},
--           MoveLearn {mldMoveName = "Spite", mldLearnMethod = LevelUp 12},
--           MoveLearn {mldMoveName = "Incinerate", mldLearnMethod = LevelUp 16},
--           MoveLearn {mldMoveName = "Confuse Ray", mldLearnMethod = LevelUp 20},
--           MoveLearn {mldMoveName = "Will-O-Wisp", mldLearnMethod = LevelUp 24},
--           MoveLearn {mldMoveName = "Extrasensory", mldLearnMethod = LevelUp 28},
--           MoveLearn {mldMoveName = "Flamethrower", mldLearnMethod = LevelUp 32},
--           MoveLearn {mldMoveName = "Imprison", mldLearnMethod = LevelUp 36},
--           MoveLearn {mldMoveName = "Fire Spin", mldLearnMethod = LevelUp 40},
--           MoveLearn {mldMoveName = "Safeguard", mldLearnMethod = LevelUp 44},
--           MoveLearn {mldMoveName = "Inferno", mldLearnMethod = LevelUp 48},
--           MoveLearn {mldMoveName = "Fire Blast", mldLearnMethod = LevelUp 52},
--           MoveLearn {mldMoveName = "Baby-Doll Eyes", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Flail", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Flame Charge", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Healing Wish", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Howl", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Hypnosis", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Memento", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Roar", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Take Down", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Charm", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Agility", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Protect", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Confuse Ray", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fire Spin", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Facade", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Hex", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Snarl", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Swift", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Flame Charge", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Endure", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sunny Day", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dig", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Zen Headbutt", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Foul Play", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Body Slam", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sleep Talk", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rest", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Imprison", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dark Pulse", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Substitute", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Will-O-Wisp", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Heat Wave", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Energy Ball", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Encore", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Flamethrower", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Helping Hand", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Baton Pass", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Nasty Plot", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fire Blast", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Overheat", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Flare Blitz", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Tera Blast", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Roar", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Spite", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Weather Ball", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Burning Jealousy", mldLearnMethod = TM}
--         ]
--   sv <- getLearnset vulp SV
--   svCorrect @=? sv

-- testAlolanVulpix :: [PokemonPartial] -> TestTree
-- testAlolanVulpix pkmnPartial =
--   let vulp = findMon "Vulpix" (Just "Alolan Vulpix") pkmnPartial
--    in testGroup
--         "Alolan Vulpix"
--         [ testCase "USUM" (testAlolanVulpixUSUM vulp),
--           testCase "SWSH" (testAlolanVulpixSWSH vulp),
--           testCase "BDSP" (testAlolanVulpixBDSP vulp),
--           testCase "SV" (testAlolanVulpixSV vulp)
--         ]

-- testAlolanVulpixUSUM :: PokemonPartial -> Assertion
-- testAlolanVulpixUSUM vulp = do
--   let usumCorrect =
--         [ MoveLearn {mldMoveName = "Powder Snow", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Tail Whip", mldLearnMethod = LevelUp 4},
--           MoveLearn {mldMoveName = "Roar", mldLearnMethod = LevelUp 7},
--           MoveLearn {mldMoveName = "Baby-Doll Eyes", mldLearnMethod = LevelUp 9},
--           MoveLearn {mldMoveName = "Ice Shard", mldLearnMethod = LevelUp 10},
--           MoveLearn {mldMoveName = "Confuse Ray", mldLearnMethod = LevelUp 12},
--           MoveLearn {mldMoveName = "Icy Wind", mldLearnMethod = LevelUp 15},
--           MoveLearn {mldMoveName = "Payback", mldLearnMethod = LevelUp 18},
--           MoveLearn {mldMoveName = "Mist", mldLearnMethod = LevelUp 20},
--           MoveLearn {mldMoveName = "Feint Attack", mldLearnMethod = LevelUp 23},
--           MoveLearn {mldMoveName = "Hex", mldLearnMethod = LevelUp 26},
--           MoveLearn {mldMoveName = "Aurora Beam", mldLearnMethod = LevelUp 28},
--           MoveLearn {mldMoveName = "Extrasensory", mldLearnMethod = LevelUp 31},
--           MoveLearn {mldMoveName = "Safeguard", mldLearnMethod = LevelUp 34},
--           MoveLearn {mldMoveName = "Ice Beam", mldLearnMethod = LevelUp 36},
--           MoveLearn {mldMoveName = "Imprison", mldLearnMethod = LevelUp 39},
--           MoveLearn {mldMoveName = "Blizzard", mldLearnMethod = LevelUp 42},
--           MoveLearn {mldMoveName = "Grudge", mldLearnMethod = LevelUp 44},
--           MoveLearn {mldMoveName = "Captivate", mldLearnMethod = LevelUp 47},
--           MoveLearn {mldMoveName = "Sheer Cold", mldLearnMethod = LevelUp 50},
--           MoveLearn {mldMoveName = "Agility", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Charm", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Disable", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Encore", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Extrasensory", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Flail", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Freeze-Dry", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Howl", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Hypnosis", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Moonblast", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Power Swap", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Secret Power", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Spite", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Tail Slap", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Aqua Tail", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Covet", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Foul Play", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Heal Bell", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Icy Wind", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Iron Tail", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Pain Split", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Role Play", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Snore", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Spite", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Zen Headbutt", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Roar", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Toxic", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Hail", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Hidden Power", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Ice Beam", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Blizzard", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Protect", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rain Dance", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Safeguard", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Frustration", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Return", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Double Team", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Facade", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rest", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Attract", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Round", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Payback", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Aurora Veil", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Psych Up", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Frost Breath", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Swagger", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sleep Talk", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Substitute", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dark Pulse", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Confide", mldLearnMethod = TM}
--         ]
--   usum <- getLearnset vulp USUM
--   usumCorrect @=? usum

-- testAlolanVulpixSWSH :: PokemonPartial -> Assertion
-- testAlolanVulpixSWSH vulp = do
--   let swshCorrect =
--         [ MoveLearn {mldMoveName = "Powder Snow", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Tail Whip", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Disable", mldLearnMethod = LevelUp 4},
--           MoveLearn {mldMoveName = "Ice Shard", mldLearnMethod = LevelUp 8},
--           MoveLearn {mldMoveName = "Spite", mldLearnMethod = LevelUp 12},
--           MoveLearn {mldMoveName = "Icy Wind", mldLearnMethod = LevelUp 16},
--           MoveLearn {mldMoveName = "Confuse Ray", mldLearnMethod = LevelUp 20},
--           MoveLearn {mldMoveName = "Aurora Beam", mldLearnMethod = LevelUp 24},
--           MoveLearn {mldMoveName = "Extrasensory", mldLearnMethod = LevelUp 28},
--           MoveLearn {mldMoveName = "Ice Beam", mldLearnMethod = LevelUp 32},
--           MoveLearn {mldMoveName = "Imprison", mldLearnMethod = LevelUp 36},
--           MoveLearn {mldMoveName = "Mist", mldLearnMethod = LevelUp 40},
--           MoveLearn {mldMoveName = "Aurora Veil", mldLearnMethod = LevelUp 44},
--           MoveLearn {mldMoveName = "Sheer Cold", mldLearnMethod = LevelUp 48},
--           MoveLearn {mldMoveName = "Grudge", mldLearnMethod = LevelUp 52},
--           MoveLearn {mldMoveName = "Blizzard", mldLearnMethod = LevelUp 56},
--           MoveLearn {mldMoveName = "Baby-Doll Eyes", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Flail", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Freeze-Dry", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Howl", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Hypnosis", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Moonblast", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Roar", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Dig", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Safeguard", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rest", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Snore", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Protect", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Icy Wind", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Charm", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Attract", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rain Dance", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Hail", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Facade", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Swift", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Imprison", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Weather Ball", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Payback", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Power Swap", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Round", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Hex", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Tail Slap", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Draining Kiss", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Body Slam", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Ice Beam", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Blizzard", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Agility", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Substitute", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Endure", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sleep Talk", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Encore", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Iron Tail", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dark Pulse", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Zen Headbutt", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Foul Play", mldLearnMethod = TM}
--         ]
--   swsh <- getLearnset vulp SWSH
--   swshCorrect @=? swsh

-- testAlolanVulpixBDSP :: PokemonPartial -> Assertion
-- testAlolanVulpixBDSP vulp = do
--   let bdspCorrect = []
--   bdsp <- getLearnset vulp BDSP
--   bdspCorrect @=? bdsp

-- testAlolanVulpixSV :: PokemonPartial -> Assertion
-- testAlolanVulpixSV vulp = do
--   let svCorrect =
--         [ MoveLearn {mldMoveName = "Powder Snow", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Tail Whip", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Disable", mldLearnMethod = LevelUp 4},
--           MoveLearn {mldMoveName = "Ice Shard", mldLearnMethod = LevelUp 8},
--           MoveLearn {mldMoveName = "Spite", mldLearnMethod = LevelUp 12},
--           MoveLearn {mldMoveName = "Icy Wind", mldLearnMethod = LevelUp 16},
--           MoveLearn {mldMoveName = "Confuse Ray", mldLearnMethod = LevelUp 20},
--           MoveLearn {mldMoveName = "Aurora Beam", mldLearnMethod = LevelUp 24},
--           MoveLearn {mldMoveName = "Extrasensory", mldLearnMethod = LevelUp 28},
--           MoveLearn {mldMoveName = "Ice Beam", mldLearnMethod = LevelUp 32},
--           MoveLearn {mldMoveName = "Imprison", mldLearnMethod = LevelUp 36},
--           MoveLearn {mldMoveName = "Mist", mldLearnMethod = LevelUp 40},
--           MoveLearn {mldMoveName = "Aurora Veil", mldLearnMethod = LevelUp 44},
--           MoveLearn {mldMoveName = "Freeze-Dry", mldLearnMethod = LevelUp 48},
--           MoveLearn {mldMoveName = "Blizzard", mldLearnMethod = LevelUp 52},
--           MoveLearn {mldMoveName = "Baby-Doll Eyes", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Flail", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Howl", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Hypnosis", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Moonblast", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Roar", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Take Down", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Charm", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fake Tears", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Agility", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Protect", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Confuse Ray", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Disarming Voice", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Chilling Water", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Facade", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Hex", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Swift", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Icy Wind", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Draining Kiss", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Stored Power", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Endure", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rain Dance", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Snowscape", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dig", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Zen Headbutt", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Foul Play", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Body Slam", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sleep Talk", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dazzling Gleam", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rest", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Imprison", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dark Pulse", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Substitute", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Encore", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Play Rough", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Helping Hand", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Baton Pass", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Ice Beam", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Misty Terrain", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Nasty Plot", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Blizzard", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Tera Blast", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Roar", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Spite", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Icicle Spear", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Weather Ball", mldLearnMethod = TM}
--         ]
--   sv <- getLearnset vulp SV
--   svCorrect @=? sv

-- testCharmander :: [PokemonPartial] -> TestTree
-- testCharmander pkmnPartial =
--   let char = findMon "Charmander" Nothing pkmnPartial
--    in testGroup
--         "Charmander"
--         [ testCase "USUM" (testCharmanderUSUM char),
--           testCase "SWSH" (testCharmanderSWSH char),
--           testCase "BDSP" (testCharmanderBDSP char),
--           testCase "SV" (testCharmanderSV char)
--         ]

-- testCharmanderUSUM :: PokemonPartial -> Assertion
-- testCharmanderUSUM char = do
--   let usumCorrect =
--         [ MoveLearn {mldMoveName = "Growl", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Scratch", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Ember", mldLearnMethod = LevelUp 7},
--           MoveLearn {mldMoveName = "Smokescreen", mldLearnMethod = LevelUp 10},
--           MoveLearn {mldMoveName = "Dragon Rage", mldLearnMethod = LevelUp 16},
--           MoveLearn {mldMoveName = "Scary Face", mldLearnMethod = LevelUp 19},
--           MoveLearn {mldMoveName = "Fire Fang", mldLearnMethod = LevelUp 25},
--           MoveLearn {mldMoveName = "Flame Burst", mldLearnMethod = LevelUp 28},
--           MoveLearn {mldMoveName = "Slash", mldLearnMethod = LevelUp 34},
--           MoveLearn {mldMoveName = "Flamethrower", mldLearnMethod = LevelUp 37},
--           MoveLearn {mldMoveName = "Fire Spin", mldLearnMethod = LevelUp 43},
--           MoveLearn {mldMoveName = "Inferno", mldLearnMethod = LevelUp 46},
--           MoveLearn {mldMoveName = "Air Cutter", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Ancient Power", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Beat Up", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Belly Drum", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Bite", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Counter", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Crunch", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Dragon Dance", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Dragon Pulse", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Dragon Rush", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Flare Blitz", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Focus Punch", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Metal Claw", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Outrage", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Dragon Pulse", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Fire Pledge", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Fire Punch", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Focus Punch", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Heat Wave", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Iron Tail", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Snore", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Thunder Punch", mldLearnMethod = Tutor},
--           MoveLearn {mldMoveName = "Work Up", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dragon Claw", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Toxic", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Hidden Power", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sunny Day", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Protect", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Frustration", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Return", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Brick Break", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Double Team", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Flamethrower", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fire Blast", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rock Tomb", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Aerial Ace", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Facade", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Flame Charge", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rest", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Attract", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Round", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Echoed Voice", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Overheat", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fling", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Will-O-Wisp", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Shadow Claw", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Swords Dance", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rock Slide", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Swagger", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sleep Talk", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Substitute", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Confide", mldLearnMethod = TM}
--         ]
--   usum <- getLearnset char USUM
--   usumCorrect @=? usum

-- testCharmanderSWSH :: PokemonPartial -> Assertion
-- testCharmanderSWSH char = do
--   let swshCorrect =
--         [ MoveLearn {mldMoveName = "Growl", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Scratch", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Ember", mldLearnMethod = LevelUp 4},
--           MoveLearn {mldMoveName = "Smokescreen", mldLearnMethod = LevelUp 8},
--           MoveLearn {mldMoveName = "Dragon Breath", mldLearnMethod = LevelUp 12},
--           MoveLearn {mldMoveName = "Fire Fang", mldLearnMethod = LevelUp 17},
--           MoveLearn {mldMoveName = "Slash", mldLearnMethod = LevelUp 20},
--           MoveLearn {mldMoveName = "Flamethrower", mldLearnMethod = LevelUp 24},
--           MoveLearn {mldMoveName = "Scary Face", mldLearnMethod = LevelUp 28},
--           MoveLearn {mldMoveName = "Fire Spin", mldLearnMethod = LevelUp 32},
--           MoveLearn {mldMoveName = "Inferno", mldLearnMethod = LevelUp 36},
--           MoveLearn {mldMoveName = "Flare Blitz", mldLearnMethod = LevelUp 40},
--           MoveLearn {mldMoveName = "Ancient Power", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Belly Drum", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Bite", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Counter", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Dragon Rush", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Dragon Tail", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Metal Claw", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Wing Attack", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Mega Punch", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Mega Kick", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fire Punch", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Thunder Punch", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fire Spin", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dig", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rest", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rock Slide", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Snore", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Protect", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Scary Face", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Attract", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sunny Day", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Beat Up", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Will-O-Wisp", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Facade", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Swift", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Helping Hand", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Brick Break", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Weather Ball", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rock Tomb", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fling", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Shadow Claw", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fire Fang", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Round", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Acrobatics", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "False Swipe", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Swords Dance", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Body Slam", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Flamethrower", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fire Blast", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Substitute", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Outrage", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Endure", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sleep Talk", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Iron Tail", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Crunch", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Heat Wave", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Overheat", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dragon Claw", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dragon Dance", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Flare Blitz", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dragon Pulse", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Work Up", mldLearnMethod = TM}
--         ]
--   swsh <- getLearnset char SWSH
--   swshCorrect @=? swsh

-- testCharmanderBDSP :: PokemonPartial -> Assertion
-- testCharmanderBDSP char = do
--   let bdspCorrect =
--         [ MoveLearn {mldMoveName = "Growl", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Scratch", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Ember", mldLearnMethod = LevelUp 4},
--           MoveLearn {mldMoveName = "Smokescreen", mldLearnMethod = LevelUp 8},
--           MoveLearn {mldMoveName = "Dragon Breath", mldLearnMethod = LevelUp 12},
--           MoveLearn {mldMoveName = "Fire Fang", mldLearnMethod = LevelUp 17},
--           MoveLearn {mldMoveName = "Slash", mldLearnMethod = LevelUp 20},
--           MoveLearn {mldMoveName = "Flamethrower", mldLearnMethod = LevelUp 24},
--           MoveLearn {mldMoveName = "Scary Face", mldLearnMethod = LevelUp 28},
--           MoveLearn {mldMoveName = "Fire Spin", mldLearnMethod = LevelUp 32},
--           MoveLearn {mldMoveName = "Inferno", mldLearnMethod = LevelUp 36},
--           MoveLearn {mldMoveName = "Flare Blitz", mldLearnMethod = LevelUp 40},
--           MoveLearn {mldMoveName = "Air Cutter", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Ancient Power", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Beat Up", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Belly Drum", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Bite", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Counter", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Crunch", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Dragon Dance", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Dragon Rush", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Dragon Tail", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Flare Blitz", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Metal Claw", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Outrage", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Wing Attack", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Focus Punch", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dragon Claw", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Work Up", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sunny Day", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Protect", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Iron Tail", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dig", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Brick Break", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Double Team", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Flamethrower", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fire Blast", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rock Tomb", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Aerial Ace", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Facade", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rest", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Attract", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Overheat", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "False Swipe", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fling", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Endure", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dragon Pulse", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Will-O-Wisp", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Shadow Claw", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Swords Dance", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rock Slide", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sleep Talk", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Swagger", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Substitute", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Cut", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Strength", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rock Smash", mldLearnMethod = TM}
--         ]
--   bdsp <- getLearnset char BDSP
--   bdspCorrect @=? bdsp

-- testCharmanderSV :: PokemonPartial -> Assertion
-- testCharmanderSV char = do
--   let svCorrect =
--         [ MoveLearn {mldMoveName = "Growl", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Scratch", mldLearnMethod = LevelUp 1},
--           MoveLearn {mldMoveName = "Ember", mldLearnMethod = LevelUp 4},
--           MoveLearn {mldMoveName = "Smokescreen", mldLearnMethod = LevelUp 8},
--           MoveLearn {mldMoveName = "Dragon Breath", mldLearnMethod = LevelUp 12},
--           MoveLearn {mldMoveName = "Fire Fang", mldLearnMethod = LevelUp 17},
--           MoveLearn {mldMoveName = "Slash", mldLearnMethod = LevelUp 20},
--           MoveLearn {mldMoveName = "Flamethrower", mldLearnMethod = LevelUp 24},
--           MoveLearn {mldMoveName = "Scary Face", mldLearnMethod = LevelUp 28},
--           MoveLearn {mldMoveName = "Fire Spin", mldLearnMethod = LevelUp 32},
--           MoveLearn {mldMoveName = "Inferno", mldLearnMethod = LevelUp 36},
--           MoveLearn {mldMoveName = "Flare Blitz", mldLearnMethod = LevelUp 40},
--           MoveLearn {mldMoveName = "Ancient Power", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Belly Drum", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Bite", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Counter", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Dragon Rush", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Dragon Tail", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Iron Tail", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Metal Claw", mldLearnMethod = Egg},
--           MoveLearn {mldMoveName = "Take Down", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Scary Face", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Protect", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fire Fang", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fire Spin", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Facade", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Metal Claw", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Swift", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rock Tomb", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Flame Charge", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fling", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dragon Tail", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Endure", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sunny Day", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dig", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "False Swipe", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Brick Break", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Shadow Claw", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Body Slam", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fire Punch", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Thunder Punch", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Sleep Talk", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dragon Claw", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rest", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Rock Slide", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Swords Dance", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dragon Dance", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Substitute", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Will-O-Wisp", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Crunch", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Dragon Pulse", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Heat Wave", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Flamethrower", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Helping Hand", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fire Blast", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Fire Pledge", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Outrage", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Overheat", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Focus Blast", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Flare Blitz", mldLearnMethod = TM},
--           MoveLearn {mldMoveName = "Tera Blast", mldLearnMethod = TM}
--         ]
--   sv <- getLearnset char SV
--   svCorrect @=? sv

-- testSobble :: [PokemonPartial] -> TestTree
-- testSobble pkmnPartial =
--   let sob = findMon "Sobble" Nothing pkmnPartial
--    in testGroup
--         "Sobble"
--         [testCase "USUM" (testSobbleUSUM sob)]

-- testSobbleUSUM :: PokemonPartial -> Assertion
-- testSobbleUSUM sob = do
--   let usumCorrect = []
--   usum <- getLearnset sob USUM
--   usumCorrect @=? usum
